In [1]:
#Imports 

import subprocess
import warnings
warnings.filterwarnings("ignore", message="numpy.dtype size changed")
warnings.filterwarnings("ignore", message="numpy.ufunc size changed")
import pandas as pd
import numpy as np
from itertools import combinations
import matplotlib.pyplot as plt
from sklearn.grid_search import GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.svm import SVC
import multiprocessing
from sklearn import svm
from sklearn.metrics import accuracy_score
import datetime
from sklearn.utils import resample
from sklearn.preprocessing import StandardScaler
import pickle
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import roc_auc_score
import itertools
import os
from subprocess import call

#random_state=101

/usr/local/lib/python2.7/dist-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/usr/local/lib/python2.7/dist-packages/sklearn/grid_search.py:42: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)

In [2]:
with open('/home/tambonis/Dropbox/Doutorado/Pesquisa/Epitopos/Epitopos_SVM_LBTOPE/Sequencias/TabelaDadosCru', 'rb') as fp:
    data = pickle.load(fp)

In [3]:
print("Shape: ", data.shape)
pd.DataFrame(data).head()

('Shape: ', (1000, 1404))

,0,1,2,3,4,5,6,7,8,9,...,1394,1395,1396,1397,1398,1399,1400,1401,1402,1403
0,65.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,10.0,5.0,...,0.005743,0.004850,0.001522,0.000000,0.0,0.000000,0.000000,0.020293,0.0,1.0
1,35.0,0.0,5.0,30.0,0.0,0.0,0.0,0.0,10.0,0.0,...,0.016962,0.016850,0.008506,0.006218,0.0,0.037306,0.000000,0.000000,0.0,1.0
2,30.0,0.0,0.0,0.0,0.0,30.0,0.0,0.0,0.0,10.0,...,0.004471,0.004235,0.004235,0.000000,0.0,0.000000,0.000000,0.088238,0.0,1.0
3,35.0,0.0,5.0,0.0,5.0,5.0,0.0,10.0,5.0,0.0,...,0.018376,0.015676,0.012582,0.009376,0.0,0.000000,0.009376,0.009376,0.0,1.0
4,55.0,0.0,0.0,0.0,5.0,15.0,0.0,0.0,10.0,5.0,...,0.000819,0.000819,0.000819,0.000000,0.0,0.000000,0.009526,0.028579,0.0,1.0

In [4]:
#Converter no formato adequado ao mrmr. 

features = []
features.append("class")
for i in range(1, data.shape[1]): features.append("feature_" + str(i))

normalizar = False

if normalizar: #Normalizar?
    scaler = StandardScaler()
    data_converted_csv = pd.DataFrame(np.column_stack((data[:,-1], 
                           scaler.fit_transform(data[:,:-1]))), columns=features)
else: 
    data_converted_csv = pd.DataFrame(np.column_stack((data[:,-1], data[:,:-1])), 
                                      columns=features)

#Salvar no formato adequado ao mrmr. 
#data_converted_csv = data_converted_csv.sample(frac=1.0) #Random data
data_converted_csv.to_csv("TabelaDadosConvertidosCSVParaMrmr.csv", header=True, index=False)

In [5]:
data_converted_csv.head()

,class,feature_1,feature_2,feature_3,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,...,feature_1394,feature_1395,feature_1396,feature_1397,feature_1398,feature_1399,feature_1400,feature_1401,feature_1402,feature_1403
0,1.0,65.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,10.0,...,0.005743,0.005743,0.004850,0.001522,0.000000,0.0,0.000000,0.000000,0.020293,0.0
1,1.0,35.0,0.0,5.0,30.0,0.0,0.0,0.0,0.0,10.0,...,0.025455,0.016962,0.016850,0.008506,0.006218,0.0,0.037306,0.000000,0.000000,0.0
2,1.0,30.0,0.0,0.0,0.0,0.0,30.0,0.0,0.0,0.0,...,0.005765,0.004471,0.004235,0.004235,0.000000,0.0,0.000000,0.000000,0.088238,0.0
3,1.0,35.0,0.0,5.0,0.0,5.0,5.0,0.0,10.0,5.0,...,0.018545,0.018376,0.015676,0.012582,0.009376,0.0,0.000000,0.009376,0.009376,0.0
4,1.0,55.0,0.0,0.0,0.0,5.0,15.0,0.0,0.0,10.0,...,0.001658,0.000819,0.000819,0.000819,0.000000,0.0,0.000000,0.009526,0.028579,0.0

In [6]:
#mrmr

call("./Comandosmrmr")

0

In [7]:
a

NameError: name 'a' is not defined

In [ ]:
#Leitura das caracterÃ­sticas selecionados pelo mrmr.

selectedfeaures = pd.read_csv("OutputmRMRGaribado", header=None, sep=" ")
selectedfeaures.columns = ["Features", "Valores"]

In [ ]:
selectedfeaures = selectedfeaures.sort_values(['Valores'], ascending=False)

In [ ]:
selectedfeaures.head()

In [ ]:
selectedfeaures.shape

# FeaturizaÃ§Ã£o

In [ ]:
features = []
for i in range(1, data.shape[1]): features.append("feature_" + str(i))
features.append("class")

data = pd.DataFrame(data, columns=features)

In [ ]:
data.shape

In [ ]:
#Fica ordenado? 

data[selectedfeaures['Features']].head(n=3)

In [ ]:
data_converted_csv['feature_755'][0:3]

In [ ]:
y = data['class']
data = np.column_stack((data[selectedfeaures['Features']], y)) #Tabela de dados featurizada.
#selectedfeaures = selectedfeaures[selectedfeaures[1]>0.0]

In [ ]:
data.shape

In [ ]:
pd.DataFrame(data).head(n=5)

In [ ]:
#Salvar os dados featurizados

with open("TabelaDadosFeaturizada", "wb") as fp:   #Pickling
    pickle.dump(data, fp)